### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by minisbett** [bl4ckscor3/Sit#36]
Modrindth lists the mod as 1.21-1.21.1 compatible, however when trying to add it to a modpack it seems to fail, despite even offering to add it to the modpack. Not sure if this is an issue with Modrindth.
![image](https://github.com/user-attachments/assets/6b4f7647-e99d-43b7-835b-6a827fe191c9)
![image](https://github.com/user-attachments/assets/aca4d5fb-e7c1-493e-8431-c89951d48b6f)

**Comment by bl4ckscor3** [comment]
If you are using Fabric/Quilt, it might have been because the file was not tagged with 1.21.1. I fixed that now, so please try again.

**Comment by minisbett** [comment]
It seems like the same issue still exists. No idea why. It happens when I search up the mod in the Modrindth app, then click on install and then click on my modpack. Usually when a mod is not available for that version, the modpack doesn't show up so I'm confused why it does show up but gives that error.

**Comment by bl4ckscor3** [comment]
I recently had someone else report a similar issue to me, where I accidentally tagged a file incorrectly and after fixing it, they still weren't able to get the Modrinth App to find the file. In the end, they had to manually download and add it before the App would show the file. I'm guessing this is a Modrinth issue, because I just tried to install this mod in a NeoForge, Fabric, and Quilt profile on the Modrinth App, and it worked just fine. Try restarting the App, and your PC. If none of that works, manual installation is an option, and perhaps talking to the folks at Modrinth directly.

**Comment by MeeniMc** [comment]
Looks like the 1.21.3 r29 is tagged for quilt only on Modrinth, and needs to be tagged for fabric as well

**Comment by bl4ckscor3** [comment]
Thank you for notifying me, I fixed it! However that's the 1.21.3 file and was released after this issue was posted, and even after my previous comment.
